# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pytwofaui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pyTwoFa(object):
    def setupUi(self, pyTwoFa):
        pyTwoFa.setObjectName("pyTwoFa")
        pyTwoFa.resize(401, 244)
        self.verticalLayout = QtWidgets.QVBoxLayout(pyTwoFa)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbStr = QtWidgets.QComboBox(pyTwoFa)
        self.cbStr.setMinimumSize(QtCore.QSize(171, 0))
        self.cbStr.setEditable(True)
        self.cbStr.setObjectName("cbStr")
        self.horizontalLayout.addWidget(self.cbStr)
        self.pbOk = QtWidgets.QPushButton(pyTwoFa)
        self.pbOk.setMaximumSize(QtCore.QSize(80, 23))
        self.pbOk.setObjectName("pbOk")
        self.horizontalLayout.addWidget(self.pbOk)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.teOutput = QtWidgets.QTextEdit(pyTwoFa)
        self.teOutput.setObjectName("teOutput")
        self.verticalLayout.addWidget(self.teOutput)

        self.retranslateUi(pyTwoFa)
        QtCore.QMetaObject.connectSlotsByName(pyTwoFa)

    def retranslateUi(self, pyTwoFa):
        _translate = QtCore.QCoreApplication.translate
        pyTwoFa.setWindowTitle(_translate("pyTwoFa", "pyTwoFa"))
        self.pbOk.setText(_translate("pyTwoFa", "确认"))
